FROM postgis/postgis

# COPY ./devops/db/load-extensions.sh /docker-entrypoint-initdb.d/
# RUN chmod 755 /docker-entrypoint-initdb.d/load-extensions.sh
COPY ./devops/db/dummy_dump.sql /docker-entrypoint-initdb.d