version: '3'
services:
  postgres:
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    build:
      context: .
      dockerfile: ./devops/db/Dockerfile.db
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
  zookeeper:
    image: zookeeper:3.4.9
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - ./data/zookeeper/data:/data
      - ./data/zookeeper/datalog:/datalog
  kafka1:
    image: confluentinc/cp-kafka:5.3.0
    hostname: kafka1
    ports:
      - "9091:9091"
    environment:
      KAFKA_ADVERTISED_LISTENERS: LISTENER_DOCKER_INTERNAL://kafka1:19091,LISTENER_DOCKER_EXTERNAL://${DOCKER_HOST_IP:-127.0.0.1}:9091
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: LISTENER_DOCKER_INTERNAL:PLAINTEXT,LISTENER_DOCKER_EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: LISTENER_DOCKER_INTERNAL
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
      KAFKA_BROKER_ID: 1
    volumes:
      - ./data/kafka1/data:/var/lib/kafka/data
    depends_on:
      - zookeeper
  kafdrop:
    image: obsidiandynamics/kafdrop
    restart: "no"
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKERCONNECT: "kafka1:19091"
    depends_on:
      - kafka1
  api:
    environment:
      DB_USERNAME: postgres
      DB_NAME: postgres
      DB_PASSWORD: 123456
      DB_HOST: postgres
      DB_PORT: 5432
      FLASK_DEBUG: 1
    build:
      context: ./modules/api
    ports:
      - '5000:5000'
    depends_on:
      - postgres
    volumes:
      - "./modules/api:/api"
  api-location:
    environment:
      DB_USERNAME: postgres
      DB_NAME: postgres
      DB_PASSWORD: 123456
      DB_HOST: postgres
      DB_PORT: 5432
      KAFKA_SERVER: kafka1:19091
    build:
      context: ./modules/api-location
    ports:
      - '5005:5005'
    depends_on:
      - postgres
      - kafka1
    command: ["./wait-for-it.sh", "kafka1:9091", "--", "python", "./main.py"]
  api-kafka:
    environment:
      DB_USERNAME: postgres
      DB_NAME: postgres
      DB_PASSWORD: 123456
      DB_HOST: postgres
      DB_PORT: 5432
      KAFKA_SERVER: kafka1:19091
    build:
      context: ./modules/api-kafka
    depends_on:
      - postgres
      - kafka1
    command: [ "./wait-for-it.sh", "kafka1:9091", "--", "python", "./main.py" ]
volumes:
  db:
    driver: local